### ISSUE TITLE
[BUG] - ffi-geos - Segmentation fault

### ISSUE THREAD

**Issue by alexstan67** [sky-unlimited/wef_2023#301]
**Describe the bug**
When we make a trip request between 2 different dates, it happens more and more often that we receive a:

> Incomplete response received from application

Impossible to go to production with this error :cry: 

**To Reproduce**
Make a trip request, and select 2 different dates... it seems random as I don't understand what triggers the error...

Hereunder the logs...
[development.log](https://github.com/user-attachments/files/15567885/development.log)

It occurs for polygon elements, in this case seems to be  `@flyzone_common_polygons`

** First analysis**

- app/services/destinations.rb:188:in `init_top_destination_airports' line 188

- /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-geos-2.4.0/lib/ffi-geos/polygon.rb:6: [BUG] Segmentation fault at 0x00007f916f3b563c
- GEOSGetNumInteriorRings_r
- /home/alex/github/sky-unlimited/wef_2023/app/services/flight_track.rb:65:in `in_flyzone?'

**Comment by christinasugiono** [comment]
I found this on [Stackoverflow](https://stackoverflow.com/questions/11738924/incomplete-response-body-being-returned-from-rails-3-app-with-rabl), maybe we can give it a try
